package org.hexrobot.fe5randomizer;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

import org.hexrobot.fe5randomizer.MainView;

public class AppTest {
    
}
